name: README Validator

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint README.md
        run: markdownlint README.md
